name: Windows environment

on:
  workflow_dispatch:

jobs:
  This-PC:
    runs-on: windows-latest
    timeout-minutes: 340

    steps:
      - name: Set variables
        shell: pwsh
        run: |
          echo "USER=standarduser" >> $env:GITHUB_ENV
          echo "PASS=${{ secrets.PASSWORD }}" >> $env:GITHUB_ENV

      - name: Install & Connect Tailscale
        shell: pwsh
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-1.92.3-amd64.msi -OutFile $env:TEMP\t.msi
          Start-Process msiexec.exe -ArgumentList "/i $env:TEMP\t.msi /quiet /norestart" -Wait

          & "$env:ProgramFiles\Tailscale\tailscale.exe" up `
            --reset `
            --authkey="${{ secrets.TAILSCALE_AUTHKEY }}" `
            --hostname=vm

          $ip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          echo "TAILSCALE_IP=$ip" >> $env:GITHUB_ENV

      - name: Create Standard User
        shell: pwsh
        run: |
          $sec = ConvertTo-SecureString $env:PASS -AsPlainText -Force
          New-LocalUser $env:USER -Password $sec -FullName "Standard User"
          Add-LocalGroupMember -Group "Users" -Member $env:USER

      - name: Enable Auto Login
        shell: pwsh
        run: |
          $key="HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"

          Set-ItemProperty $key AutoAdminLogon "1"
          Set-ItemProperty $key DefaultUserName $env:USER
          Set-ItemProperty $key DefaultPassword $env:PASS
          Set-ItemProperty $key DefaultDomainName "."

      - name: Create Elevated First Logon Task
        shell: pwsh
        run: |
          $scriptPath="C:\init.ps1"
          $url="https://raw.githubusercontent.com/djameledin/untitled/main/untitled.ps1"

          Invoke-WebRequest $url -OutFile $scriptPath

          $action = New-ScheduledTaskAction -Execute "PowerShell.exe" -Argument "-ExecutionPolicy Bypass -File $scriptPath"
          $trigger = New-ScheduledTaskTrigger -AtLogOn
          $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest

          Register-ScheduledTask -TaskName "FirstLogonInit" -Action $action -Trigger $trigger -Principal $principal -Force

      - name: Final Info
        shell: pwsh
        run: |
          Write-Host "VM ready"
          Write-Host "User: $env:USER"
          Write-Host "IP: $env:TAILSCALE_IP"
